pipeline:
  tests:
    image: node
    commands:
      - yarn
      - yarn test
    when:
      event: [push, tag]

  docker-staging:
    image: plugins/docker
    repo: nossas/bonde-graphql
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-staging:
    image: appleboy/drone-ssh
    host: staging.bonde.org
    username: ubuntu
    secrets: [ ssh_key ]
    command_timeout: 120
    port: 22
    secrets: [ ssh_key ]
    script:
      - sudo docker pull nossas/bonde-graphql:${DRONE_BRANCH}
      - sudo docker tag nossas/bonde-graphql:${DRONE_BRANCH} dokku/data:latest
      - dokku tags:deploy data latest
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  docker-production:
    image: plugins/docker
    repo: nossas/bonde-graphql
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  deploy-production:
    image: appleboy/drone-ssh
    host: ssh.bonde.org
    username: ubuntu
    secrets: [ ssh_key ]
    command_timeout: 120
    port: 22
    secrets: [ ssh_key ]
    script:
      - sudo docker pull nossas/bonde-graphql:${DRONE_TAG##v}
      - sudo docker tag nossas/bonde-graphql:${DRONE_TAG##v} dokku/data:latest
      - dokku tags:deploy data latest
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
